export const HoursObjOne = {
  id: "hours",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Wpadnij nas odwiedzić",
  headline: "Godziny otwarcia",
  description:
    "Gdybyśmy tylko mogli, gotowalibyśmy dla Was całą dobę w każdy dzień tygodnia. Niestety też musimy udać się czasem na siestę, dlatego jesteśmy dostępni dla naszych ukochanych gości w tych godzinach. Zapraszamy serdecznie na południowy lunch, popołudniowy obiad czy wieczorne jedzenie.",
  imgStart: true,
  img: require("../../images/hours.jpg"),
  alt: "Godziny",
  dark: true,
  primary: false,
  darkText: true,
  showButton: false,
  //open hours per day:
  monday: "Poniedziałek",
  freeDays: "Wtorek, środa",
  tuesday: "Czwartek",
  friday: "Piątek",
  saturday: "Sobota",
  sunday: "Niedziela",
  siesta: "¡Viva la Siesta!",
  hoursToTwenty: "12.00-20.00",
  hoursToTwentyOne: "12.00-21.00",
};
