export const ContactObjOne = {
  id: "contact",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Skontaktuj się z nami!",
  headline: "Kontakt",
  phone: "+48 737 855 501",
  imgStart: false,
  img: require("../../images/logo.png"),
  alt: "Godziny",
  dark: true,
  primary: false,
  darkText: false,
  showButton: false,
};
